# yaml-language-server: $schema=https://schema.blue-build.org/recipe-v1.json
# image will be published to ghcr.io/<user>/<name>
name: bazzite-ai
description: This is pre-install some AI tools OS image.

base-image: ghcr.io/ublue-os/bazzite-gdx
image-version: latest

modules:

  # Install downgraded kernel for ROCm support and other packages
  - type: rpm-ostree
    install:
      - rpm-build
      - rpmdevtools
      - gcc
      - make
      - git
      - obs-studio
      - flatpak-xdg-utils
      - snapd

  - type: systemd
    system:
      enabled:
        - snapd
        - snapd.socket

  - type: containerfile
    snippets:
      - RUN ln -sf /var/lib/snapd/snap /snap || true
#      - RUN snap wait system seed.loaded
      - RUN snap install juju --classic
      - RUN juju deploy kubeflow --channel 1.10/stable


  # Install Charmed Kubeflow tools
#  - type: script
#    scripts:
#      - install_kubeflow.sh
