# yaml-language-server: $schema=https://schema.blue-build.org/module-stage-list-v1.json
modules:
  - type: rpm-ostree
    install:
      - snapd

  - type: systemd
    system:
      enabled:
        - snapd
        - snapd.socket

  - type: containerfile
    snippets:
      - RUN ln -sf /var/lib/snapd/snap /snap || true

  - type: containerfile
    snippets:
      - RUN ls
#      - RUN snap wait system seed.loaded
#      - RUN snap install juju --classic

  - from-file: juju.yml

  - type: script
    scripts:
      - fix_roothome_permissions.sh

  - type: containerfile
    snippets:
      - RUN ls
#      - RUN snap wait system seed.loaded
#      - RUN snap install juju --classic